set @tenantid = ?;


delete from billentity_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id=@tenantid );
delete from billtemplate_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id=@tenantid );
delete from billtplgroup_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id=@tenantid );
delete from billitem_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id=@tenantid );
delete from bill_base where cBillNo='cn_ref_orgs' and tenant_id=@tenantid ;

select ifnull(max(id),0)+1 into @id4 from bill_base;
insert into bill_base(`id`,`cBillNo`,`cName`,`cCardKey`,`cSubId`,`iDefTplId`,`iDefPrnTplId`,`iOrder`,`bAllowMultiTpl`,`cDefWhere`,`isDeleted`,`bPrintLimited`,`iSystem`,`cAuthId`,`cBillType`,`cBeanId`,`cFilterId`,`bRowAuthControl`,`bColumnAuthControl`,`bRowAuthObject`,`bColumnAuthControlled`,`bRowAuthControlled`,`cPersonDataSource`,`cCarry`,`authGroupKey`,`tenant_id`) values (@id4,'cn_ref_orgs','cn测试组织参照',null,'CNPF',null,null,0,0,null,0,null,1,null,'TreeList',null,null,0,0,0,0,0,null,null,null,@tenantid);

select ifnull(max(id),0)+1 into @id9 from billentity_base;
insert into billentity_base(`id`,`iBillId`,`cCode`,`cName`,`cSubId`,`iOrder`,`isDeleted`,`cDataSourceName`,`cPrimaryKey`,`iSystem`,`bMain`,`cForeignKey`,`cParentCode`,`childrenField`,`cModelType`,`bIsNull`,`tenant_id`) values (@id9,@id4,'cn_ref_orgs','行政组织','CNPF',1,0,null,'id',1,0,null,null,null,null,null,@tenantid);

select ifnull(max(id),0)+1 into @id14 from billtemplate_base;
insert into billtemplate_base(`id`,`iBillId`,`cName`,`iOrder`,`iTplMode`,`iWidth`,`isDeleted`,`cPrintSetting`,`cPageHeader`,`cPageFooter`,`cTitleHeight`,`iPrintTotal`,`iFixedCols`,`cMemo`,`cTitle`,`iGridStyle`,`cRowLayout`,`cTitleStyle`,`cTotalColor`,`cAmongColor`,`cFixedColor`,`tenant_id`) values (@id14,@id4,'cn测试行政组织参照',0,0,'10000',0,null,null,null,null,null,null,null,'cn测试行政组织参照',null,null,null,null,null,null,@tenantid);

select ifnull(max(id),0)+1 into @id19 from billtplgroup_base;
insert into billtplgroup_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`cCode`,`cName`,`cSubId`,`iOrder`,`cDataSourceName`,`cPrimaryKey`,`isDeleted`,`iSystem`,`bMain`,`cForeignKey`,`cParentDataSource`,`cType`,`iParentID`,`cAlign`,`iCols`,`cStyle`,`cImage`,`tenant_id`) values (@id19,@id4,@id9,@id14,'Title','行政组织','CNPF',1,null,'id',0,1,0,null,null,'SearchTree',null,'left',null,null,null,@tenantid);

select ifnull(max(id),0)+1 into @id24 from billitem_base;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id24,@id4,@id9,@id14,@id19,'CNPF','code','code','来源系统编码','来源系统编码','108',null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'100',null,null,null,1,null,0,null,null,null,0,1,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,@tenantid);
set @id25=@id24+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id25,@id4,@id9,@id14,@id19,'CNPF','name','name','来源系统名称','来源系统名称','108',null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'100',null,null,null,1,null,null,null,null,null,1,1,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,@tenantid);
set @id26=@id25+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id26,@id4,@id9,@id14,@id19,'CNPF','id','id','ID','ID','108',null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,'100',null,null,null,1,null,null,null,null,null,7,1,null,null,null,null,null,null,null,'InputNumber',null,null,0,null,null,null,0,0,@tenantid);
set @id27=@id26+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id27,@id4,@id9,@id14,@id19,'CNPF','ts','pubts','时间戳','时间戳','108',null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,1,null,null,null,1,null,null,null,null,null,8,1,null,null,null,null,null,null,null,'datepicker',null,null,0,null,null,null,0,0,@tenantid);

update bill_base set `iDefTplId`=@id14 where `id`=@id4;
update bill_base a ,bill_base b set a.cFilterId=b.cFilterId,a.sysid=b.id where a.cBillNo = b.cBillNo And b.tenant_id = @tenantid And a.id = @id4;
insert into pb_filter_solution_common (`solutionId`,`itemId`,`itemName`,`itemTitle`,`refType`,`isCommon`,`rangeInput`,`multSelect`,`compareLogic`,`defaultVal1`,`defaultVal2`,`orderId`,`saveHistory`,`checkRefer`,`tenant_id`,`defineId`,`itemType`,`refercode`)  select `solutionId`,`itemId`,`itemName`,`itemTitle`,`refType`,`isCommon`,`rangeInput`,`multSelect`,`compareLogic`,`defaultVal1`,`defaultVal2`,`orderId`,`saveHistory`,`checkRefer`,@tenantid,`defineId`,`itemType`,`refercode` from pb_filter_solution_common  where tenant_id=@tenantid and solutionId=(select id from pb_filter_solution where filtersId=(select cFilterId from bill_base where tenant_id=@tenantid and cBillNo='cn_ref_orgs'));
Update billitem_base left join userdef_base on billitem_base.cSelfDefineType=userdef_base.defineId and userdef_base.tenant_id=@tenantid left join userdef_type on userdef_base.type = userdef_type.deftype set billitem_base.cshowcaption=userdef_base.showitem,billitem_base.bHidden=0,billitem_base.bShowIt=1,billitem_base.cControlType=userdef_type.controltype, billitem_base.refReturn=(case when userdef_base.type='Archive' then 'name' else NULL END), billitem_base.cRefType=(case when userdef_base.type='Archive' then 'pb_userdefine' else NULL END) where iBillId = (select id from bill_base where cbillno='cn_ref_orgs' and tenant_id=@tenantid) and billitem_base.tenant_id=@tenantid and bSelfDefine=1 and userdef_base.isenabled=1;




delete from billentity_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id=1292161350684928 );
delete from billtemplate_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id=1292161350684928 );
delete from billtplgroup_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id=1292161350684928 );
delete from billitem_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id=1292161350684928 );
delete from bill_base where cBillNo='cn_demo_user' and tenant_id=1292161350684928 ;

select ifnull(max(id),0)+1 into @id4 from bill_base;
insert into bill_base(`id`,`cBillNo`,`cName`,`cCardKey`,`cSubId`,`iDefTplId`,`iDefPrnTplId`,`iOrder`,`bAllowMultiTpl`,`cDefWhere`,`isDeleted`,`bPrintLimited`,`iSystem`,`cAuthId`,`cBillType`,`cBeanId`,`cFilterId`,`bRowAuthControl`,`bColumnAuthControl`,`bRowAuthObject`,`bColumnAuthControlled`,`bRowAuthControlled`,`cPersonDataSource`,`cCarry`,`authGroupKey`,`tenant_id`) values (@id4,'cn_demo_user','自定义档案参照',null,'devPlat',null,null,0,0,null,0,null,1,null,'ArchiveList',null,null,0,0,0,0,0,null,null,null,1292161350684928);

select ifnull(max(id),0)+1 into @id9 from billentity_base;
insert into billentity_base(`id`,`iBillId`,`cCode`,`cName`,`cSubId`,`iOrder`,`isDeleted`,`cDataSourceName`,`cPrimaryKey`,`iSystem`,`bMain`,`cForeignKey`,`cParentCode`,`childrenField`,`cModelType`,`bIsNull`,`tenant_id`) values (@id9,@id4,'cn_demo_user','自定义档案','devPlat',null,0,null,'id',1,1,null,null,null,null,null,1292161350684928);

select ifnull(max(id),0)+1 into @id14 from billtemplate_base;
insert into billtemplate_base(`id`,`iBillId`,`cName`,`iOrder`,`iTplMode`,`iWidth`,`isDeleted`,`cPrintSetting`,`cPageHeader`,`cPageFooter`,`cTitleHeight`,`iPrintTotal`,`iFixedCols`,`cMemo`,`cTitle`,`iGridStyle`,`cRowLayout`,`cTitleStyle`,`cTotalColor`,`cAmongColor`,`cFixedColor`,`tenant_id`) values (@id14,@id4,'自定义档案参照显示模板',0,0,'10000',0,null,null,null,null,null,null,null,'自定义档案',null,null,null,null,null,null,1292161350684928);

select ifnull(max(id),0)+1 into @id19 from billtplgroup_base;
insert into billtplgroup_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`cCode`,`cName`,`cSubId`,`iOrder`,`cDataSourceName`,`cPrimaryKey`,`isDeleted`,`iSystem`,`bMain`,`cForeignKey`,`cParentDataSource`,`cType`,`iParentID`,`cAlign`,`iCols`,`cStyle`,`cImage`,`tenant_id`) values (@id19,@id4,@id9,@id14,'Table_3','Table','devPlat',3,null,'id',0,1,1,null,null,'Table',null,'center',null,null,null,1292161350684928);

select ifnull(max(id),0)+1 into @id24 from billitem_base;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id24,@id4,@id9,@id14,@id19,'aa','code','code','编码','编码',1,null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,1,null,null,null,'200',null,null,null,1,null,0,null,null,null,0,0,null,null,null,null,null,'desc',null,'Input',null,null,0,null,null,null,0,0,1292161350684928);
set @id25=@id24+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id25,@id4,@id9,@id14,@id19,'aa','name','name','名称','名称',3,null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'200',null,null,null,1,null,1,null,null,null,0,0,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,1292161350684928);
set @id26=@id25+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id26,@id4,@id9,@id14,@id19,'aa','id','id','ID','ID',3,null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,'200',null,null,null,0,null,0,null,null,null,7,0,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,1292161350684928);

update bill_base set `iDefTplId`=@id14 where `id`=@id4;
update bill_base a ,bill_base b set a.cFilterId=b.cFilterId,a.sysid=b.id where a.cBillNo = b.cBillNo And b.tenant_id = @tenantid And a.id = @id4;
insert into pb_filter_solution_common (`solutionId`,`itemId`,`itemName`,`itemTitle`,`refType`,`isCommon`,`rangeInput`,`multSelect`,`compareLogic`,`defaultVal1`,`defaultVal2`,`orderId`,`saveHistory`,`checkRefer`,`tenant_id`,`defineId`,`itemType`,`refercode`)  select `solutionId`,`itemId`,`itemName`,`itemTitle`,`refType`,`isCommon`,`rangeInput`,`multSelect`,`compareLogic`,`defaultVal1`,`defaultVal2`,`orderId`,`saveHistory`,`checkRefer`,1292161350684928,`defineId`,`itemType`,`refercode` from pb_filter_solution_common  where tenant_id=@tenantid and solutionId=(select id from pb_filter_solution where filtersId=(select cFilterId from bill_base where tenant_id=@tenantid and cBillNo='cn_demo_user'));
Update billitem_base left join userdef_base on billitem_base.cSelfDefineType=userdef_base.defineId and userdef_base.tenant_id=1292161350684928 left join userdef_type on userdef_base.type = userdef_type.deftype set billitem_base.cshowcaption=userdef_base.showitem,billitem_base.bHidden=0,billitem_base.bShowIt=1,billitem_base.cControlType=userdef_type.controltype, billitem_base.refReturn=(case when userdef_base.type='Archive' then 'name' else NULL END), billitem_base.cRefType=(case when userdef_base.type='Archive' then 'pb_userdefine' else NULL END) where iBillId = (select id from bill_base where cbillno='cn_demo_user' and tenant_id=1292161350684928) and billitem_base.tenant_id=1292161350684928 and bSelfDefine=1 and userdef_base.isenabled=1