INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel1', 'T1', '技术', 'technique', '技術', '', '', '', 1, '技术初级', 'techniqueprimary', '技術初級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel2', 'T2', '技术', 'technique', '技術', '', '', '', 2, '技术中级', 'techniqueintermediate', '技術中級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel3', 'T3', '技术', 'technique', '技術', '', '', '', 3, '技术高级', 'techniquesenior', '技術高級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');

INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel4', 'M1', '管理', 'management', '管理', '', '', '', 1, '管理初级', 'managementprimary', '管理初級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel5', 'M2', '管理', 'management', '管理', '', '', '', 2, '管理中级', 'managementintermediate', '管理中級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel6', 'M3', '管理', 'management', '管理', '', '', '', 3, '管理高级', 'managementsenior', '管理高級', '', '', '', '', '', '', '', '2020-02-17 21:26:32.000', 0, 0, 'super');

INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel7', 'X1', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试初级', 'managementprimary', '测试初级', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel8', 'X2', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试中级', 'managementmediate', '测试中级', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel9', 'X3', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试高级', 'managementsenior', '测试高级', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel10', 'X4', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试技师', 'management1', '测试技师', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel11', 'X5', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试高级技师', 'management2', '测试高级技师', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');
INSERT INTO `demo_ranks`(`ID`, `CODE`, `TYPE`, `TYPE2`, `TYPE3`, `TYPE4`, `TYPE5`, `TYPE6`, `GRADE`, `name`, `POST_LEVEL2`, `POST_LEVEL3`, `POST_LEVEL4`, `POST_LEVEL5`, `POST_LEVEL6`, `CREATE_TIME`, `CREATE_USER`, `LAST_MODIFIED`, `LAST_MODIFY_USER`, `TS`, `DR`, `BPM_STATE`, `TENANT_ID`) VALUES ('superlevel12', 'X6', '测试', 'test', '测试', NULL, NULL, NULL, 3, '测试助理工程师', 'management3', '测试助理工程师', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2020-02-17 21:26:32.000', 0, 0, 'super');