-- 此脚本作为开发示例预制数据参考使用。
-- 严禁将此脚本直接或修改后在数据库中执行,如由上述行为引发问题,概不支持。
###编码规则###
##INSERT INTO `aa_regist_conf` (`systemCode`, `configKey`, `servicePath`, `domain`, `serviceType`, `id`, `pubts`, `label`, `displayName`) VALUES ('CNPF', 'billcode', NULL, 'iuap-billcode-web', 'rest', '294', now(), NULL, NULL);
###调度任务-领域应用树注册###
##INSERT INTO `aa_regist_conf` (`systemCode`, `configKey`, `servicePath`, `domain`, `serviceType`, `id`, `pubts`) VALUES ('CNPF', 'dispatch', NULL, 'devmodel-cn-mainsub-multiple', 'rpc', '295', now());
###预警任务-左侧树###
##INSERT INTO `aa_regist_conf` (`systemCode`, `configKey`, `servicePath`, `domain`, `serviceType`, `id`, `pubts`) VALUES ('CNPF', 'prewarning', NULL, 'devmodel-cn-mainsub-multiple', 'rpc', '296',now());


delete from billentity_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' );
delete from billtemplate_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' );
delete from billtplgroup_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' );
delete from billitem_base where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' );
delete from pub_makebillrule_detail where makebill_id in (select makebill_id from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' ));
delete from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' );
delete from bill_base where cBillNo='cn_ref_orgs' and tenant_id='0' ;

select ifnull(max(id),0)+1 into @id4 from bill_base;
insert into bill_base(`id`,`cBillNo`,`cName`,`cCardKey`,`cSubId`,`iDefTplId`,`iDefPrnTplId`,`iOrder`,`bAllowMultiTpl`,`cDefWhere`,`isDeleted`,`bPrintLimited`,`iSystem`,`cAuthId`,`cBillType`,`cBeanId`,`cFilterId`,`bRowAuthControl`,`bColumnAuthControl`,`bRowAuthObject`,`bColumnAuthControlled`,`bRowAuthControlled`,`cPersonDataSource`,`cCarry`,`authGroupKey`,`tenant_id`) values (@id4,'cn_ref_orgs','cn测试组织参照',null,'devPlat',null,null,0,0,null,0,null,1,null,'TreeList',null,null,0,0,0,0,0,null,null,null,0);

select ifnull(max(id),0)+1 into @id9 from billentity_base;
insert into billentity_base(`id`,`iBillId`,`cCode`,`cName`,`cSubId`,`iOrder`,`isDeleted`,`cDataSourceName`,`cPrimaryKey`,`iSystem`,`bMain`,`cForeignKey`,`cParentCode`,`childrenField`,`cModelType`,`bIsNull`,`tenant_id`) values (@id9,@id4,'cn_ref_orgs','行政组织','devPlat',1,0,null,'id',1,0,null,null,null,null,null,0);

select ifnull(max(id),0)+1 into @id14 from billtemplate_base;
insert into billtemplate_base(`id`,`iBillId`,`cName`,`iOrder`,`iTplMode`,`iWidth`,`isDeleted`,`cPrintSetting`,`cPageHeader`,`cPageFooter`,`cTitleHeight`,`iPrintTotal`,`iFixedCols`,`cMemo`,`cTitle`,`iGridStyle`,`cRowLayout`,`cTitleStyle`,`cTotalColor`,`cAmongColor`,`cFixedColor`,`tenant_id`) values (@id14,@id4,'cn测试行政组织参照',0,0,'10000',0,null,null,null,null,null,null,null,'cn测试行政组织参照',null,null,null,null,null,null,0);

select ifnull(max(id),0)+1 into @id19 from billtplgroup_base;
insert into billtplgroup_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`cCode`,`cName`,`cSubId`,`iOrder`,`cDataSourceName`,`cPrimaryKey`,`isDeleted`,`iSystem`,`bMain`,`cForeignKey`,`cParentDataSource`,`cType`,`iParentID`,`cAlign`,`iCols`,`cStyle`,`cImage`,`tenant_id`) values (@id19,@id4,@id9,@id14,'Title','行政组织','devPlat',1,null,'id',0,1,0,null,null,'SearchTree',null,'left',null,null,null,0);

select ifnull(max(id),0)+1 into @id24 from billitem_base;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id24,@id4,@id9,@id14,@id19,'devPlat','code','code','来源系统编码','来源系统编码','108',null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'100',null,null,null,1,null,0,null,null,null,0,1,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,0);
set @id25=@id24+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id25,@id4,@id9,@id14,@id19,'devPlat','name','name','来源系统名称','来源系统名称','108',null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'100',null,null,null,1,null,null,null,null,null,1,1,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,0);
set @id26=@id25+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id26,@id4,@id9,@id14,@id19,'devPlat','id','id','ID','ID','108',null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,'100',null,null,null,1,null,null,null,null,null,7,1,null,null,null,null,null,null,null,'InputNumber',null,null,0,null,null,null,0,0,0);
set @id27=@id26+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id27,@id4,@id9,@id14,@id19,'devPlat','ts','pubts','时间戳','时间戳','108',null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,1,null,null,null,1,null,null,null,null,null,8,1,null,null,null,null,null,null,null,'datepicker',null,null,0,null,null,null,0,0,0);

update bill_base set `iDefTplId`=@id14 where `id`=@id4;
update pub_ref set cFilterId=@id42 where cbillnum = 'cn_ref_orgs';




delete from billentity_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' );
delete from billtemplate_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' );
delete from billtplgroup_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' );
delete from billitem_base where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' );
delete from pub_makebillrule_detail where makebill_id in (select makebill_id from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' ));
delete from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='cn_demo_user' and tenant_id='0' );
delete from bill_base where cBillNo='cn_demo_user' and tenant_id='0' ;

select ifnull(max(id),0)+1 into @id4 from bill_base;
insert into bill_base(`id`,`cBillNo`,`cName`,`cCardKey`,`cSubId`,`iDefTplId`,`iDefPrnTplId`,`iOrder`,`bAllowMultiTpl`,`cDefWhere`,`isDeleted`,`bPrintLimited`,`iSystem`,`cAuthId`,`cBillType`,`cBeanId`,`cFilterId`,`bRowAuthControl`,`bColumnAuthControl`,`bRowAuthObject`,`bColumnAuthControlled`,`bRowAuthControlled`,`cPersonDataSource`,`cCarry`,`authGroupKey`,`tenant_id`) values (@id4,'cn_demo_user','自定义档案参照',null,'devPlat',null,null,0,0,null,0,null,1,null,'ArchiveList',null,null,0,0,0,0,0,null,null,null,0);

select ifnull(max(id),0)+1 into @id9 from billentity_base;
insert into billentity_base(`id`,`iBillId`,`cCode`,`cName`,`cSubId`,`iOrder`,`isDeleted`,`cDataSourceName`,`cPrimaryKey`,`iSystem`,`bMain`,`cForeignKey`,`cParentCode`,`childrenField`,`cModelType`,`bIsNull`,`tenant_id`) values (@id9,@id4,'cn_demo_user','自定义档案','devPlat',null,0,null,'id',1,1,null,null,null,null,null,0);

select ifnull(max(id),0)+1 into @id14 from billtemplate_base;
insert into billtemplate_base(`id`,`iBillId`,`cName`,`iOrder`,`iTplMode`,`iWidth`,`isDeleted`,`cPrintSetting`,`cPageHeader`,`cPageFooter`,`cTitleHeight`,`iPrintTotal`,`iFixedCols`,`cMemo`,`cTitle`,`iGridStyle`,`cRowLayout`,`cTitleStyle`,`cTotalColor`,`cAmongColor`,`cFixedColor`,`tenant_id`) values (@id14,@id4,'自定义档案参照显示模板',0,0,'10000',0,null,null,null,null,null,null,null,'自定义档案',null,null,null,null,null,null,0);

select ifnull(max(id),0)+1 into @id19 from billtplgroup_base;
insert into billtplgroup_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`cCode`,`cName`,`cSubId`,`iOrder`,`cDataSourceName`,`cPrimaryKey`,`isDeleted`,`iSystem`,`bMain`,`cForeignKey`,`cParentDataSource`,`cType`,`iParentID`,`cAlign`,`iCols`,`cStyle`,`cImage`,`tenant_id`) values (@id19,@id4,@id9,@id14,'Table_3','Table','devPlat',3,null,'id',0,1,1,null,null,'Table',null,'center',null,null,null,0);

select ifnull(max(id),0)+1 into @id24 from billitem_base;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id24,@id4,@id9,@id14,@id19,'aa','code','code','编码','编码',1,null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'200',null,null,null,1,null,0,null,null,null,0,0,null,null,null,null,null,'desc',null,'Input',null,null,0,null,null,null,0,0,0);
set @id25=@id24+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id25,@id4,@id9,@id14,@id19,'aa','name','name','名称','名称',3,null,1,null,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'200',null,null,null,1,null,1,null,null,null,0,0,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,0);
set @id26=@id25+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id26,@id4,@id9,@id14,@id19,'aa','id','id','ID','ID',3,null,1,null,null,0,1,1,null,null,null,null,null,null,null,null,0,null,null,null,'200',null,null,null,0,null,0,null,null,null,7,0,null,null,null,null,null,null,null,'Input',null,null,0,null,null,null,0,0,0);

update bill_base set `iDefTplId`=@id14 where `id`=@id4;
update pub_ref set cFilterId=@id41 where cbillnum = 'cn_demo_user';

INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (1, 'cn_ref_orgs', 'cn组织测试参照', 'cn组织测试参照', 'cn_ref_orgs', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Tree', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_ref_orgs', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (6, 'cn_ref_depts', '部门列表', '部门列表', 'cn_ref_depts', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Table', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_ref_depts', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (3, 'cn_demo_user', '自定义参照', '自定义参照', 'cn_demo_user', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Table', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_demo_user', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (8, 'cn_demo_dept', '部门树卡', '部门树卡', 'cn_demo_dept', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Tree', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_demo_dept', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (10, 'cn_test_user', '自定义参照', '自定义参照', 'cn_test_user', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Table', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_demo_user', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
INSERT INTO `pub_ref`(`id`, `code`, `name`, `description`, `reftype`, `isorgrel`, `datasourcetype`, `datasourcesql`, `datasourcegridsql`, `iparentrefid`, `csub_id`, `centitykeyfld`, `ctpltype`, `centitynamefld`, `cretfld`, `bmultisel`, `creffiltersql`, `cautocompletefiltersql`, `bauth`, `ccheckflds`, `ctipprefix`, `ctipfld`, `ifilterstyle`, `ishowstyle`, `bpage`, `lPageSize`, `cdatagrid_fullname`, `cdatagrid_classfk`, `cdataclass_fullname`, `cdataclass_refclsname`, `bdataclass_rule`, `bdataclass_retenddata`, `cdataclass_lscode`, `cdataclass_lsname`, `cdataclass_sortfield`, `clsname`, `sortfield`, `cbillnum`, `eventbean`, `svcKey`, `cFilterId`, `authType`, `extendField`, `domain`) VALUES (11, 'cn_post_level', '职级参照', '职级参照', 'cn_post_level', NULL, 'rpc', NULL, NULL, NULL, 'CNPF', 'id', 'Table', 'name', 'code', b'0', '0', NULL, b'0', 'code,name', NULL, NULL, NULL, NULL, b'0', NULL, NULL, NULL, NULL, 'name', NULL, NULL, 'code', 'name', NULL, NULL, NULL, 'cn_demo_user', NULL, NULL, NULL, NULL, NULL, 'iuap5-u8c');
